require("lazy").setup({
	"lunarvim/darkplus.nvim",
	require("plugins.treesitter"),
	require("plugins.lsp"),
	require("plugins.snippets"),
	require("plugins.completion"),
	require("plugins.notifications"),
	require("plugins.file-explorer"),
	require("plugins.telescope"),
	require("plugins.statusline"),
	require("plugins.git"),
	require("plugins.signature"),
	require("plugins.comments"),
})
